### ISSUE TITLE
trackScreenWithName() does nothing with eventName parameter

### ISSUE THREAD

**Issue by sohail-bakhtiari** [poitch/dart-matomo#19]
The trackScreenWithName() method does nothing with eventName parameter. Maybe this should be added at line #239:
`eventName: eventName,`

Or am I missing a point?

**Comment by poitch** [comment]
Looking at the Matomo SDK ([Android in particular](https://github.com/matomo-org/matomo-sdk-android/blob/master/tracker/src/main/java/org/matomo/sdk/extra/TrackHelper.java))

They don't seem to allow eventName at all. I originally copied the code from the other Matomo library which had the eventName as a parameter for trackScreenWithName() but I guess that parameter shouldn't be used at all, and it probably needs to be removed so it is less confusing.

**Comment by sohail-bakhtiari** [comment]
True. Adding that line doesn't help. I will use `MatomoTracker.trackEvent()` instead.
Thanks for quick reply.
