### ISSUE TITLE
Add option for `token_auth` param

### ISSUE THREAD

**Issue by JulianBissekkou** [poitch/dart-matomo#31]
It would be nice to provide the param `token_auth` which is needed when a request is processed after a day.

**Comment by JulianBissekkou** [comment]
Pull request is ready. Would be nice if you can merge and publish a new version :)
Thanks a lot! @poitch

**Comment by saibotma** [comment]
Have been waiting for this. A quick merge would be awesome 😎

**Comment by stefanschaller** [comment]
Thanks, @JulianBissekkou  Looks fantastic. A new version for pub would be great

**Comment by poitch** [comment]
I'll take of this in a few hours, I'm currently busy with work stuff.

**Comment by JulianBissekkou** [comment]
Any updates?

**Comment by poitch** [comment]
Sorry, the last few days were quite busy. I merged and published 1.1.0 with your change. Thank you for contributing.
